DROP TABLE IF EXISTS playlists CASCADE;

CREATE TABLE playlists (
  id SERIAL PRIMARY KEY NOT NULL,
  song_external_id BIGINT NOT NULL UNIQUE,
  title VARCHAR(75) NOT NULL,
  song_like INTEGER DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);