DROP TABLE IF EXISTS client_users CASCADE;

CREATE TABLE client_users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(255) unique NOT NULL,
  password_digest VARCHAR(255) NOT NULL CHECK (LENGTH(password_digest) >= 7),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  admin_role_id INTEGER REFERENCES admin_roles(id) ON DELETE CASCADE
);